CREATE TABLE IF NOT EXISTS country(
   country_pkey VARCHAR (50) UNIQUE PRIMARY KEY,
   display_name VARCHAR (50),
   two_letter_iso VARCHAR (2) NOT NULL DEFAULT '',
   three_letter_iso VARCHAR (3) NOT NULL DEFAULT ''
);

INSERT INTO country (country_pkey, display_name, two_letter_iso, three_letter_iso) VALUES
	('afghanistan', 'Afghanistan', 'af', 'afg'),
	('albania', 'Albania', 'al', 'alb'),
	('algeria', 'Algeria', 'dz', 'dza'),
	('american samoa', 'American Samoa', 'as', 'asm'),
	('andorra', 'Andorra', 'ad', 'and'),
	('angola', 'Angola', 'ao', 'ago'),
	('anguilla', 'Anguilla', 'ai', 'aia'),
	('antarctica', 'Antarctica', 'aq', 'ata'),
	('antigua and barbuda', 'Antigua and Barbuda', 'ag', 'atg'),
	('argentina', 'Argentina', 'ar', 'arg'),
	('armenia', 'Armenia', 'am', 'arm'),
	('aruba', 'Aruba', 'aw', 'abw'),
	('australia', 'Australia', 'au', 'aus'),
	('austria', 'Austria', 'at', 'aut'),
	('azerbaijan', 'Azerbaijan', 'az', 'aze'),
	('bahamas', 'Bahamas', 'bs', 'bhs'),
	('bahrain', 'Bahrain', 'bh', 'bhr'),
	('bangladesh', 'Bangladesh', 'bd', 'bgd'),
	('barbados', 'Barbados', 'bb', 'brb'),
	('belarus', 'Belarus', 'by', 'blr'),
	('belgium', 'Belgium', 'be', 'bel'),
	('belize', 'Belize', 'bz', 'blz'),
	('benin', 'Benin', 'bj', 'ben'),
	('bermuda', 'Bermuda', 'bm', 'bmu'),
	('bhutan', 'Bhutan', 'bt', 'btn'),
	('bolivia', 'Bolivia', 'bo', 'bol'),
	('bosnia and herzegovina', 'Bosnia and Herzegovina', 'ba', 'bih'),
	('botswana', 'Botswana', 'bw', 'bwa'),
	('brazil', 'Brazil', 'br', 'bra'),
	('british indian ocean territory', 'British Indian Ocean Territory', 'io', 'iot'),
	('british virgin islands', 'British Virgin Islands', 'vg', 'vgb'),
	('brunei', 'Brunei', 'bn', 'brn'),
	('bulgaria', 'Bulgaria', 'bg', 'bgr'),
	('burkina faso', 'Burkina Faso', 'bf', 'bfa'),
	('burundi', 'Burundi', 'bi', 'bdi'),
	('cambodia', 'Cambodia', 'kh', 'khm'),
	('cameroon', 'Cameroon', 'cm', 'cmr'),
	('canada', 'Canada', 'ca', 'can'),
	('cape verde', 'Cape Verde', 'cv', 'cpv'),
	('cayman islands', 'Cayman Islands', 'ky', 'cym'),
	('central african republic', 'Central African Republic', 'cf', 'caf'),
	('chad', 'Chad', 'td', 'tcd'),
	('chile', 'Chile', 'cl', 'chl'),
	('china', 'China', 'cn', 'chn'),
	('christmas island', 'Christmas Island', 'cx', 'cxr'),
	('cocos islands', 'Cocos Islands', 'cc', 'cck'),
	('colombia', 'Colombia', 'co', 'col'),
	('comoros', 'Comoros', 'km', 'com'),
	('cook islands', 'Cook Islands', 'ck', 'cok'),
	('costa rica', 'Costa Rica', 'cr', 'cri'),
	('croatia', 'Croatia', 'hr', 'hrv'),
	('cuba', 'Cuba', 'cu', 'cub'),
	('curacao', 'Curacao', 'cw', 'cuw'),
	('cyprus', 'Cyprus', 'cy', 'cyp'),
	('czech republic', 'Czech Republic', 'cz', 'cze'),
	('democratic republic of the congo', 'Democratic Republic of the Congo', 'cd', 'cod'),
	('denmark', 'Denmark', 'dk', 'dnk'),
	('djibouti', 'Djibouti', 'dj', 'dji'),
	('dominica', 'Dominica', 'dm', 'dma'),
	('dominican republic', 'Dominican Republic', 'do', 'dom'),
	('east timor', 'East Timor', 'tl', 'tls'),
	('ecuador', 'Ecuador', 'ec', 'ecu'),
	('egypt', 'Egypt', 'eg', 'egy'),
	('el salvador', 'El Salvador', 'sv', 'slv'),
	('equatorial guinea', 'Equatorial Guinea', 'gq', 'gnq'),
	('eritrea', 'Eritrea', 'er', 'eri'),
	('estonia', 'Estonia', 'ee', 'est'),
	('ethiopia', 'Ethiopia', 'et', 'eth'),
	('falkland islands', 'Falkland Islands', 'fk', 'flk'),
	('faroe islands', 'Faroe Islands', 'fo', 'fro'),
	('fiji', 'Fiji', 'fj', 'fji'),
	('finland', 'Finland', 'fi', 'fin'),
	('france', 'France', 'fr', 'fra'),
	('french polynesia', 'French Polynesia', 'pf', 'pyf'),
	('gabon', 'Gabon', 'ga', 'gab'),
	('gambia', 'Gambia', 'gm', 'gmb'),
	('georgia', 'Georgia', 'ge', 'geo'),
	('germany', 'Germany', 'de', 'deu'),
	('ghana', 'Ghana', 'gh', 'gha'),
	('gibraltar', 'Gibraltar', 'gi', 'gib'),
	('greece', 'Greece', 'gr', 'grc'),
	('greenland', 'Greenland', 'gl', 'grl'),
	('grenada', 'Grenada', 'gd', 'grd'),
	('guam', 'Guam', 'gu', 'gum'),
	('guatemala', 'Guatemala', 'gt', 'gtm'),
	('guernsey', 'Guernsey', 'gg', 'ggy'),
	('guinea', 'Guinea', 'gn', 'gin'),
	('guinea-bissau', 'Guinea-Bissau', 'gw', 'gnb'),
	('guyana', 'Guyana', 'gy', 'guy'),
	('haiti', 'Haiti', 'ht', 'hti'),
	('honduras', 'Honduras', 'hn', 'hnd'),
	('hong kong', 'Hong Kong', 'hk', 'hkg'),
	('hungary', 'Hungary', 'hu', 'hun'),
	('iceland', 'Iceland', 'is', 'isl'),
	('india', 'India', 'in', 'ind'),
	('indonesia', 'Indonesia', 'id', 'idn'),
	('iran', 'Iran', 'ir', 'irn'),
	('iraq', 'Iraq', 'iq', 'irq'),
	('ireland', 'Ireland', 'ie', 'irl'),
	('isle of man', 'Isle of Man', 'im', 'imn'),
	('israel', 'Israel', 'il', 'isr'),
	('italy', 'Italy', 'it', 'ita'),
	('ivory coast', 'Ivory Coast', 'ci', 'civ'),
	('jamaica', 'Jamaica', 'jm', 'jam'),
	('japan', 'Japan', 'jp', 'jpn'),
	('jersey', 'Jersey', 'je', 'jey'),
	('jordan', 'Jordan', 'jo', 'jor'),
	('kazakhstan', 'Kazakhstan', 'kz', 'kaz'),
	('kenya', 'Kenya', 'ke', 'ken'),
	('kiribati', 'Kiribati', 'ki', 'kir'),
	('kosovo', 'Kosovo', 'xk', 'xkx'),
	('kuwait', 'Kuwait', 'kw', 'kwt'),
	('kyrgyzstan', 'Kyrgyzstan', 'kg', 'kgz'),
	('laos', 'Laos', 'la', 'lao'),
	('latvia', 'Latvia', 'lv', 'lva'),
	('lebanon', 'Lebanon', 'lb', 'lbn'),
	('lesotho', 'Lesotho', 'ls', 'lso'),
	('liberia', 'Liberia', 'lr', 'lbr'),
	('libya', 'Libya', 'ly', 'lby'),
	('liechtenstein', 'Liechtenstein', 'li', 'lie'),
	('lithuania', 'Lithuania', 'lt', 'ltu'),
	('luxembourg', 'Luxembourg', 'lu', 'lux'),
	('macau', 'Macau', 'mo', 'mac'),
	('macedonia', 'Macedonia', 'mk', 'mkd'),
	('madagascar', 'Madagascar', 'mg', 'mdg'),
	('malawi', 'Malawi', 'mw', 'mwi'),
	('malaysia', 'Malaysia', 'my', 'mys'),
	('maldives', 'Maldives', 'mv', 'mdv'),
	('mali', 'Mali', 'ml', 'mli'),
	('malta', 'Malta', 'mt', 'mlt'),
	('marshall islands', 'Marshall Islands', 'mh', 'mhl'),
	('mauritania', 'Mauritania', 'mr', 'mrt'),
	('mauritius', 'Mauritius', 'mu', 'mus'),
	('mayotte', 'Mayotte', 'yt', 'myt'),
	('mexico', 'Mexico', 'mx', 'mex'),
	('micronesia', 'Micronesia', 'fm', 'fsm'),
	('moldova', 'Moldova', 'md', 'mda'),
	('monaco', 'Monaco', 'mc', 'mco'),
	('mongolia', 'Mongolia', 'mn', 'mng'),
	('montenegro', 'Montenegro', 'me', 'mne'),
	('montserrat', 'Montserrat', 'ms', 'msr'),
	('morocco', 'Morocco', 'ma', 'mar'),
	('mozambique', 'Mozambique', 'mz', 'moz'),
	('myanmar', 'Myanmar', 'mm', 'mmr'),
	('namibia', 'Namibia', 'na', 'nam'),
	('nauru', 'Nauru', 'nr', 'nru'),
	('nepal', 'Nepal', 'np', 'npl'),
	('netherlands', 'Netherlands', 'nl', 'nld'),
	('netherlands antilles', 'Netherlands Antilles', 'an', 'ant'),
	('new caledonia', 'New Caledonia', 'nc', 'ncl'),
	('new zealand', 'New Zealand', 'nz', 'nzl'),
	('nicaragua', 'Nicaragua', 'ni', 'nic'),
	('niger', 'Niger', 'ne', 'ner'),
	('nigeria', 'Nigeria', 'ng', 'nga'),
	('niue', 'Niue', 'nu', 'niu'),
	('north korea', 'North Korea', 'kp', 'prk'),
	('northern mariana islands', 'Northern Mariana Islands', 'mp', 'mnp'),
	('norway', 'Norway', 'no', 'nor'),
	('oman', 'Oman', 'om', 'omn'),
	('pakistan', 'Pakistan', 'pk', 'pak'),
	('palau', 'Palau', 'pw', 'plw'),
	('palestine', 'Palestine', 'ps', 'pse'),
	('panama', 'Panama', 'pa', 'pan'),
	('papua new guinea', 'Papua New Guinea', 'pg', 'png'),
	('paraguay', 'Paraguay', 'py', 'pry'),
	('peru', 'Peru', 'pe', 'per'),
	('philippines', 'Philippines', 'ph', 'phl'),
	('pitcairn', 'Pitcairn', 'pn', 'pcn'),
	('poland', 'Poland', 'pl', 'pol'),
	('portugal', 'Portugal', 'pt', 'prt'),
	('puerto rico', 'Puerto Rico', 'pr', 'pri'),
	('qatar', 'Qatar', 'qa', 'qat'),
	('republic of the congo', 'Republic of the Congo', 'cg', 'cog'),
	('reunion', 'Reunion', 're', 'reu'),
	('romania', 'Romania', 'ro', 'rou'),
	('russia', 'Russia', 'ru', 'rus'),
	('rwanda', 'Rwanda', 'rw', 'rwa'),
	('saint barthelemy', 'Saint Barthelemy', 'bl', 'blm'),
	('saint helena', 'Saint Helena', 'sh', 'shn'),
	('saint kitts and nevis', 'Saint Kitts and Nevis', 'kn', 'kna'),
	('saint lucia', 'Saint Lucia', 'lc', 'lca'),
	('saint martin', 'Saint Martin', 'mf', 'maf'),
	('saint pierre and miquelon', 'Saint Pierre and Miquelon', 'pm', 'spm'),
	('saint vincent and the grenadines', 'Saint Vincent and the Grenadines', 'vc', 'vct'),
	('samoa', 'Samoa', 'ws', 'wsm'),
	('san marino', 'San Marino', 'sm', 'smr'),
	('sao tome and principe', 'Sao Tome and Principe', 'st', 'stp'),
	('saudi arabia', 'Saudi Arabia', 'sa', 'sau'),
	('senegal', 'Senegal', 'sn', 'sen'),
	('serbia', 'Serbia', 'rs', 'srb'),
	('seychelles', 'Seychelles', 'sc', 'syc'),
	('sierra leone', 'Sierra Leone', 'sl', 'sle'),
	('singapore', 'Singapore', 'sg', 'sgp'),
	('sint maarten', 'Sint Maarten', 'sx', 'sxm'),
	('slovakia', 'Slovakia', 'sk', 'svk'),
	('slovenia', 'Slovenia', 'si', 'svn'),
	('solomon islands', 'Solomon Islands', 'sb', 'slb'),
	('somalia', 'Somalia', 'so', 'som'),
	('south africa', 'South Africa', 'za', 'zaf'),
	('south korea', 'South Korea', 'kr', 'kor'),
	('south sudan', 'South Sudan', 'ss', 'ssd'),
	('spain', 'Spain', 'es', 'esp'),
	('sri lanka', 'Sri Lanka', 'lk', 'lka'),
	('sudan', 'Sudan', 'sd', 'sdn'),
	('suriname', 'Suriname', 'sr', 'sur'),
	('svalbard and jan mayen', 'Svalbard and Jan Mayen', 'sj', 'sjm'),
	('swaziland', 'Swaziland', 'sz', 'swz'),
	('sweden', 'Sweden', 'se', 'swe'),
	('switzerland', 'Switzerland', 'ch', 'che'),
	('syria', 'Syria', 'sy', 'syr'),
	('taiwan', 'Taiwan', 'tw', 'twn'),
	('tajikistan', 'Tajikistan', 'tj', 'tjk'),
	('tanzania', 'Tanzania', 'tz', 'tza'),
	('thailand', 'Thailand', 'th', 'tha'),
	('togo', 'Togo', 'tg', 'tgo'),
	('tokelau', 'Tokelau', 'tk', 'tkl'),
	('tonga', 'Tonga', 'to', 'ton'),
	('trinidad and tobago', 'Trinidad and Tobago', 'tt', 'tto'),
	('tunisia', 'Tunisia', 'tn', 'tun'),
	('turkey', 'Turkey', 'tr', 'tur'),
	('turkmenistan', 'Turkmenistan', 'tm', 'tkm'),
	('turks and caicos islands', 'Turks and Caicos Islands', 'tc', 'tca'),
	('tuvalu', 'Tuvalu', 'tv', 'tuv'),
	('u.s. virgin islands', 'U.S. Virgin Islands', 'vi', 'vir'),
	('uganda', 'Uganda', 'ug', 'uga'),
	('ukraine', 'Ukraine', 'ua', 'ukr'),
	('united arab emirates', 'United Arab Emirates', 'ae', 'are'),
	('united kingdom', 'United Kingdom', 'gb', 'gbr'),
	('united states', 'United States', 'us', 'usa'),
	('uruguay', 'Uruguay', 'uy', 'ury'),
	('uzbekistan', 'Uzbekistan', 'uz', 'uzb'),
	('vanuatu', 'Vanuatu', 'vu', 'vut'),
	('vatican', 'Vatican', 'va', 'vat'),
	('venezuela', 'Venezuela', 've', 'ven'),
	('vietnam', 'Vietnam', 'vn', 'vnm'),
	('wallis and futuna', 'Wallis and Futuna', 'wf', 'wlf'),
	('western sahara', 'Western Sahara', 'eh', 'esh'),
	('yemen', 'Yemen', 'ye', 'yem'),
	('zambia', 'Zambia', 'zm', 'zmb'),
	('zimbabwe', 'Zimbabwe', 'zw', 'zwe');